import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} p-3`}>
                <nav className="my-5">
                    <ul className="sm:flex gap-3 p-3 bg-gray-800 text-white rounded-lg shadow-lg">
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/">Home</Link>
                        </li>
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/about">About</Link>
                        </li>
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/contact">Contact</Link>
                        </li>
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/address">Address</Link>
                        </li>
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/blogs">Blogs</Link>
                        </li>
                        <li className="hover:text-yellow-500 transition-colors duration-300">
                            <Link href="/posts">Posts</Link>
                        </li>
                    </ul>
                </nav>
                {children}
            </body>
        </html>
    );
}
